version: '3.8'

services:
  # Django Web Application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=healmymind.settings
      - MONGODB_URI=mongodb://mongodb:27017/healmymind
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
    networks:
      - healmymind_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod --bind_ip_all
    networks:
      - healmymind_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Celery and Caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - healmymind_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery:
    build: .
    command: celery -A healmymind worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=healmymind.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mongodb
    networks:
      - healmymind_network
    healthcheck:
      test: celery -A healmymind inspect ping
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Beat for Periodic Tasks
  celery-beat:
    build: .
    command: celery -A healmymind beat -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=healmymind.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mongodb
    networks:
      - healmymind_network

  # Flower for Celery Monitoring
  flower:
    build: .
    command: celery -A healmymind flower
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=healmymind.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery
    networks:
      - healmymind_network

  # Nginx for Static Files and Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - healmymind_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  mongodb_config:
  redis_data:
  static_volume:
  media_volume:

networks:
  healmymind_network:
    driver: bridge
