services:
  - type: web
    name: healmymind-backend
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn healmymind.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".render.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://healmymind.vercel.app,http://localhost:3000"
      - key: SECRET_KEY
        generateValue: true
