services:
  - type: web
    name: healmymind-backend
    runtime: python
    plan: free
    pythonVersion: 3.9.18
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn healmymind.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".render.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://healmymind.vercel.app,http://localhost:3000"
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
