apiVersion: v1
kind: Namespace
metadata:
  name: healmymind

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healmymind-web
  namespace: healmymind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healmymind-web
  template:
    metadata:
      labels:
        app: healmymind-web
    spec:
      containers:
      - name: web
        image: healmymind/web:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "healmymind.settings"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: healmymind-secrets
              key: mongodb-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: healmymind-secrets
              key: django-secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healmymind-celery
  namespace: healmymind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healmymind-celery
  template:
    metadata:
      labels:
        app: healmymind-celery
    spec:
      containers:
      - name: celery
        image: healmymind/web:latest
        command: ["celery"]
        args: ["-A", "healmymind", "worker", "-l", "info"]
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: healmymind-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healmymind-celery-beat
  namespace: healmymind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healmymind-celery-beat
  template:
    metadata:
      labels:
        app: healmymind-celery-beat
    spec:
      containers:
      - name: celery-beat
        image: healmymind/web:latest
        command: ["celery"]
        args: ["-A", "healmymind", "beat", "-l", "info"]
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: healmymind-secrets
              key: redis-url

---
apiVersion: v1
kind: Service
metadata:
  name: healmymind-web
  namespace: healmymind
spec:
  selector:
    app: healmymind-web
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healmymind-ingress
  namespace: healmymind
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.healmymindai.com
    secretName: healmymind-tls
  rules:
  - host: api.healmymindai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: healmymind-web
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: healmymind-web-hpa
  namespace: healmymind
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: healmymind-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: healmymind-config
  namespace: healmymind
data:
  DJANGO_SETTINGS_MODULE: "healmymind.settings"
  ALLOWED_HOSTS: "api.healmymindai.com,localhost"
  DEBUG: "False"

---
apiVersion: v1
kind: Secret
metadata:
  name: healmymind-secrets
  namespace: healmymind
type: Opaque
data:
  django-secret-key: ${BASE64_ENCODED_SECRET_KEY}
  mongodb-uri: ${BASE64_ENCODED_MONGODB_URI}
  redis-url: ${BASE64_ENCODED_REDIS_URL}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: healmymind-web-pdb
  namespace: healmymind
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: healmymind-web
